export default {
  resultCode: 0,
  data: {
    questionnaireId: 2,
    basic: {
      patientName: 'xxx',
      mobile: '14566667777',
      cardNo: '440100881111222234',
      idenNo: '440100881111222234123',
      age: 28,
      fullAddress: 'address 123',
      questionnaireSubjectList: [
        {
            "Id":"a563a6ad-db07-42a5-ba21-2ca4f4f73fe6",
            "Title":"1. 就诊患者近14天是否有以下症状：（发热、干咳、乏力、咽痛、嗅（味道）觉减退、鼻塞、流涕、结膜炎、肌痛、腹泻、其它症状）？",
            "SubjectType":2,
            "SubjectTypeName":"单选题",
            "SubOptions":[
                {
                    "Key":"0",
                    "Value":"否",
                    "Subs":null
                },
                {
                    "Key":"1",
                    "Value":"是",
                    "Subs":[
                        {
                            "Id":"b20c0c92-6208-4370-9db5-ed69ab156f91",
                            "Title":"具体症状是：",
                            "SubjectType":3,
                            "SubjectTypeName":"多选题",
                            "SubOptions":[
                                {
                                    "Key":"1.0",
                                    "Value":"发热",
                                    "Subs":null
                                },
                                {
                                    "Key":"1.1",
                                    "Value":"干咳",
                                    "Subs":null
                                },
                                {
                                    "Key":"1.2",
                                    "Value":"乏力",
                                    "Subs":null
                                },
                                {
                                    "Key":"1.3",
                                    "Value":"腹泻",
                                    "Subs":null
                                },
                                {
                                    "Key":"1.4",
                                    "Value":"咽痛",
                                    "Subs":null
                                },
                                {
                                    "Key":"1.5",
                                    "Value":"嗅（味）觉减退",
                                    "Subs":null
                                },
                                {
                                    "Key":"1.6",
                                    "Value":"鼻塞",
                                    "Subs":null
                                },
                                {
                                    "Key":"1.7",
                                    "Value":"流涕",
                                    "Subs":null
                                },
                                {
                                    "Key":"1.8",
                                    "Value":"结膜炎",
                                    "Subs":null
                                },
                                {
                                    "Key":"1.9",
                                    "Value":"肌痛",
                                    "Subs":null
                                }
                            ],
                            "Answer":null,
                            "Sort":1
                        },
                        {
                            "Id":"efee76cd-ee49-40cf-aa9c-0c53070bbe54",
                            "Title":"其他症状是：",
                            "SubjectType":1,
                            "SubjectTypeName":"填空题",
                            "SubOptions":null,
                            "Answer":null,
                            "Sort":2
                        }
                    ]
                }
            ],
            "Answer":null,
            "Sort":1
        },
        {
            "Id":"2e037fe6-29a5-454b-92b1-e9037fdc0ac4",
            "Title":"体温：",
            "SubjectType":1,
            "SubjectTypeName":"填空题",
            "SubOptions":null,
            "Answer":null,
            "Sort":2
        },
        {
            "Id":"7e8beb9f-e6fd-4465-979a-8a98a68df995",
            "Title":"2. 近28天内是否有境外及中高风险地区旅居史？",
            "SubjectType":2,
            "SubjectTypeName":"单选题",
            "SubOptions":[
                {
                    "Key":"0",
                    "Value":"否",
                    "Subs":null
                },
                {
                    "Key":"1",
                    "Value":"是",
                    "Subs":[
                        {
                            "Id":"0f68f8fe-ba5a-4512-8168-80c6f6177b92",
                            "Title":"具体：",
                            "SubjectType":1,
                            "SubjectTypeName":"填空题",
                            "SubOptions":null,
                            "Answer":null,
                            "Sort":1
                        }
                    ]
                }
            ],
            "Answer":null,
            "Sort":3
        },
        {
            "Id":"fbd28a91-3e08-4195-8be1-944e38dbe862",
            "Title":"3. 近21天内是否有境外及中高风险地区人员接触时？",
            "SubjectType":2,
            "SubjectTypeName":"单选题",
            "SubOptions":[
                {
                    "Key":"0",
                    "Value":"否",
                    "Subs":null
                },
                {
                    "Key":"1",
                    "Value":"是",
                    "Subs":[
                        {
                            "Id":"4c8c26b7-5df5-478c-a4b3-9537574ab9dc",
                            "Title":"具体：",
                            "SubjectType":1,
                            "SubjectTypeName":"填空题",
                            "SubOptions":null,
                            "Answer":null,
                            "Sort":1
                        }
                    ]
                }
            ],
            "Answer":null,
            "Sort":4
        },
        {
            "Id":"6991fa60-328e-4481-b96a-2ab5e8c5ffc1",
            "Title":"4. 近21天内是否有国内新冠疫情中高风险地区旅居史人员接触史？",
            "SubjectType":2,
            "SubjectTypeName":"单选题",
            "SubOptions":[
                {
                    "Key":"0",
                    "Value":"否",
                    "Subs":null
                },
                {
                    "Key":"1",
                    "Value":"是",
                    "Subs":[
                        {
                            "Id":"27fa0d4f-05f8-4ce3-8796-8a930d4bb4c5",
                            "Title":"具体：",
                            "SubjectType":1,
                            "SubjectTypeName":"填空题",
                            "SubOptions":null,
                            "Answer":null,
                            "Sort":1
                        }
                    ]
                }
            ],
            "Answer":null,
            "Sort":5
        },
        {
            "Id":"4c4939a2-c6ae-4f65-9bef-110ae07852f3",
            "Title":"5. 近14天内您的家庭、办公室、学校或托幼机构班级、车间等集体单位是否出现2例及以上发热或呼吸道症状的聚集性病例？",
            "SubjectType":2,
            "SubjectTypeName":"单选题",
            "SubOptions":[
                {
                    "Key":"0",
                    "Value":"无",
                    "Subs":null
                },
                {
                    "Key":"1",
                    "Value":"有",
                    "Subs":null
                }
            ],
            "Answer":null,
            "Sort":6
        },
        {
            "Id":"6f5dddd0-3311-4ae0-bbd0-bb8bf91d58d3",
            "Title":"6. 近14天内从哪个地区来广州？",
            "SubjectType":2,
            "SubjectTypeName":"单选题",
            "SubOptions":[
                {
                    "Key":"a",
                    "Value":"一直在广州",
                    "Subs":[
                        {
                            "Id":"949b7bc2-4355-434a-8c20-31c9ec03feb3",
                            "Title":"填写区：",
                            "SubjectType":1,
                            "SubjectTypeName":"填空题",
                            "SubOptions":null,
                            "Answer":null,
                            "Sort":1
                        }
                    ]
                },
                {
                    "Key":"b",
                    "Value":"国内",
                    "Subs":[
                        {
                            "Id":"ebef4b1e-e2f4-4854-ae6b-d2f90ecd402e",
                            "Title":"填写省：",
                            "SubjectType":1,
                            "SubjectTypeName":"填空题",
                            "SubOptions":null,
                            "Answer":null,
                            "Sort":1
                        },
                        {
                            "Id":"c56ac1a7-0813-4b55-923e-0c7bfb3e0847",
                            "Title":"填写市：",
                            "SubjectType":1,
                            "SubjectTypeName":"填空题",
                            "SubOptions":null,
                            "Answer":null,
                            "Sort":2
                        },
                        {
                            "Id":"bac76eb5-d482-4005-957b-837954b948fd",
                            "Title":"填写区：",
                            "SubjectType":1,
                            "SubjectTypeName":"填空题",
                            "SubOptions":null,
                            "Answer":null,
                            "Sort":3
                        }
                    ]
                },
                {
                    "Key":"c",
                    "Value":"境外",
                    "Subs":[
                        {
                            "Id":"6cff336c-9f64-4ec8-96a8-8681f1da0699",
                            "Title":"",
                            "SubjectType":2,
                            "SubjectTypeName":"单选题",
                            "SubOptions":[
                                {
                                    "Key":"c0",
                                    "Value":"香港",
                                    "Subs":null
                                },
                                {
                                    "Key":"c1",
                                    "Value":"澳门",
                                    "Subs":null
                                },
                                {
                                    "Key":"c2",
                                    "Value":"台湾",
                                    "Subs":null
                                },
                                {
                                    "Key":"c3",
                                    "Value":"其他",
                                    "Subs":[
                                        {
                                            "Id":"51a3e993-25d5-4fa5-896a-9d0140320b99",
                                            "Title":"填写国家或地区：",
                                            "SubjectType":1,
                                            "SubjectTypeName":"填空题",
                                            "SubOptions":null,
                                            "Answer":null,
                                            "Sort":1
                                        }
                                    ]
                                }
                            ],
                            "Answer":null,
                            "Sort":1
                        }
                    ]
                }
            ],
            "Answer":null,
            "Sort":6
        }
    ]
    }
  }
}