export interface OrderParams {
  hospitalId: string,
  branchId: string,
  patientId: string,
  patientName: string,
  deptId: string,
  deptName: string,
  doctorId: string,
  doctorName: string,
  regDate: string,
  scheduleId: string,
  timeSlice: string,
  sliceId: string,
  sqNo: string,
  startTime: string,
  endTime: string,
  sourceType: string,
  sourceId: string,
  regNo: string,
  feeType: string,
  regFee: number | string,
  treatFee: number | string,
  address: string
}